// Factor Analysis Presentation using Touying
#import "@preview/touying:0.5.3": *
#import themes.university: *

#show: university-theme.with(
  aspect-ratio: "16-9",
  config-info(
    title: [Factor Analysis & PCA],
    subtitle: [Latent Variable Modeling and Dimensionality Reduction],
    author: [Juliho Castillo Colmenares],
    date: none,
    institution: [Tec de Monterrey],
    logo: none,
  ),
  config-colors(
    primary: rgb("#003366"),
    secondary: rgb("#1E88E5"),
    tertiary: rgb("#666666"),
  ),
)

#show link: set text(fill: rgb("#1E88E5"))

#title-slide()

// ============================================================================
// PART 1: OVERVIEW & MOTIVATION
// ============================================================================

#slide[
  = Today's Agenda

  + Introduction to Dimensionality Reduction
  + Principal Component Analysis (PCA) Review
  + The Common Factor Model (FA)
  + Factor Extraction & Communalities
  + Factor Rotation (Orthogonal vs. Oblique)
  + PCA vs. Factor Analysis: Methodological Comparison
  + Suitability Testing (KMO & Bartlett's)
  + Practical Python Implementation & Educational Case Study
]

#slide[
  = Motivation: The Curse of Dimensionality

  *Why reduce dimensions in multivariate data?*

  - *High Collinearity:* Redundant predictors destabilize regression and inference.
  - *Interpretability:* Condense dozens of observed indicators into underlying constructs.
  - *Visualization:* Project $p$-dimensional data onto 2D or 3D coordinate planes.
  - *Noise Reduction:* Separate shared systematic signal from item-specific measurement noise.

  #v(0.8em)

  #grid(
    columns: (1fr, 1fr),
    gutter: 1.5em,
    [
      *Principal Component Analysis (PCA)*
      - Data-driven / Variance maximization
      - Linear combinations of all variance
      - Orthogonal components by design
    ],
    [
      *Exploratory Factor Analysis (EFA)*
      - Theory-driven / Latent construct modeling
      - Partitions *common* vs. *unique* variance
      - Rotatable for domain interpretability
    ]
  )
]

// ============================================================================
// PART 2: PRINCIPAL COMPONENT ANALYSIS (PCA)
// ============================================================================

#slide[
  = Principal Component Analysis (PCA)

  *Objective:* Transform $p$ correlated variables $X_1, \dots, X_p$ into uncorrelated components $Y_1, \dots, Y_p$ ordered by variance.

  #v(0.5em)

  *Mathematical Foundation:*
  Given covariance matrix $\mathbf{S}$ or correlation matrix $\mathbf{R}$:
  $ \mathbf{S} = \mathbf{V} \mathbf{\Lambda} \mathbf{V}^T $

  where $\mathbf{\Lambda} = \operatorname{diag}(\lambda_1, \lambda_2, \dots, \lambda_p)$ with $\lambda_1 \ge \lambda_2 \ge \dots \ge \lambda_p \ge 0$, and $\mathbf{V} = [\mathbf{v}_1, \dots, \mathbf{v}_p]$ are orthonormal eigenvectors.

  #v(0.5em)

  *Principal Components:*
  $ Y_i = \mathbf{v}_i^T (\mathbf{X} - \bar{\mathbf{x}}), \quad \operatorname{Var}(Y_i) = \lambda_i, \quad \operatorname{Cov}(Y_i, Y_j) = 0 \ (i \neq j) $
]

#slide[
  = Component Retention Criteria

  #grid(
    columns: (1fr, 1fr),
    gutter: 1.2em,
    [
      *1. Kaiser-Guttman Criterion:*
      - Retain components with eigenvalues $\lambda_i > 1$ (for standardized $\mathbf{R}$).
      - Explains more variance than a single original variable.

      #v(0.5em)
      *2. Cumulative Variance Threshold:*
      - Retain enough components to explain $70\% - 85\%$ of total variance:
      $ \frac{\sum_{i=1}^k \lambda_i}{\sum_{j=1}^p \lambda_j} \ge \text{threshold} $
    ],
    [
      *3. Scree Plot (Cattell):*
      - Plot $\lambda_i$ vs. component index $i$.
      - Identify the "elbow" where the curve levels off.

      #v(0.5em)
      *4. Parallel Analysis:*
      - Compare empirical eigenvalues against eigenvalues simulated from random data of identical dimensions.
    ]
  )
]

// ============================================================================
// PART 3: THE COMMON FACTOR MODEL
// ============================================================================

#slide[
  = The Common Factor Model

  *Hypothesis:* Observed variables $X_1, \dots, X_p$ are generated by $k < p$ unobserved *latent factors* $F_1, \dots, F_k$ plus unique errors.

  #v(0.5em)

  *Vector Formulation:*
  $ \mathbf{X} - \boldsymbol{\mu} = \mathbf{\Lambda} \mathbf{F} + \boldsymbol{\varepsilon} $

  where:
  - $\mathbf{X} = [X_1, \dots, X_p]^T$: Observed variables vector.
  - $\mathbf{\Lambda} \in \mathbb{R}^{p \times k}$: Factor loadings matrix ($\lambda_{j i} = \text{loading of } X_j \text{ on } F_i$).
  - $\mathbf{F} = [F_1, \dots, F_k]^T$: Latent common factor scores ($\mathbb{E}[\mathbf{F}] = \mathbf{0}, \operatorname{Cov}(\mathbf{F}) = \mathbf{I}_k$).
  - $\boldsymbol{\varepsilon} = [\varepsilon_1, \dots, \varepsilon_p]^T$: Specific / unique error vector ($\operatorname{Cov}(\boldsymbol{\varepsilon}) = \mathbf{\Psi} = \operatorname{diag}(\psi_1^2, \dots, \psi_p^2)$).
]

#slide[
  = Variance Partitioning: Communality & Uniqueness

  For standardized variables, total variance of $X_j$ equals 1:
  $ \operatorname{Var}(X_j) = \underbrace{\sum_{i=1}^k \lambda_{j i}^2}_{h_j^2 \text{ (Communality)}} + \underbrace{\psi_j^2}_{\text{Uniqueness}} = 1 $

  #v(0.8em)

  *Key Metrics:*
  - *Communality ($h_j^2$):* Proportion of $X_j$'s variance explained by the shared $k$ common factors ($h_j^2 \in [0, 1]$).
  - *Uniqueness ($\psi_j^2 = 1 - h_j^2$):* Variance specific to variable $X_j$ (specific factor + measurement error).
  - *Reproduced Correlation Matrix:*
  $ \hat{\mathbf{R}} = \mathbf{\Lambda} \mathbf{\Lambda}^T + \mathbf{\Psi} $
]

// ============================================================================
// PART 4: FACTOR EXTRACTION & ROTATION
// ============================================================================

#slide[
  = Factor Extraction Methods

  *1. Principal Axis Factoring (PAF):*
  - Iteratively estimates communalities along the diagonal of $\mathbf{R} - \hat{\mathbf{\Psi}}$.
  - Non-parametric; does not require multivariate normality.

  #v(0.8em)

  *2. Maximum Likelihood (ML) Extraction:*
  - Assumes multivariate normal data: $\mathbf{X} \sim \mathcal{N}_p(\boldsymbol{\mu}, \mathbf{\Sigma})$.
  - Maximizes the log-likelihood of observing sample covariance $\mathbf{S}$.
  - Provides statistical hypothesis tests ($\chi^2$ goodness-of-fit) for the number of factors $k$.
]

#slide[
  = Factor Rotation: Achieving Simple Structure

  *The Rotation Problem:* Initial factor extraction is mathematically indeterminate up to an orthogonal matrix transformation $\mathbf{T}$ ($\mathbf{\Lambda}^* = \mathbf{\Lambda}\mathbf{T}$).

  #v(0.5em)

  *Thurstone's Simple Structure:* Each variable should have large loadings on *only one* factor and near-zero loadings on others.

  #v(0.5em)

  #table(
    columns: (1.5fr, 2fr, 2fr, 2fr),
    align: (left, left, left, left),
    table.header([*Method*], [*Type*], [*Factor Correlation*], [*Best For*]),
    [Varimax], [Orthogonal], [$\operatorname{Cov}(F_i, F_j) = 0$], [Distinct, independent concepts],
    [Quartimax], [Orthogonal], [$\operatorname{Cov}(F_i, F_j) = 0$], [Simplifying rows (variables)],
    [Promax], [Oblique], [$\operatorname{Cov}(F_i, F_j) \neq 0$], [Realistic correlated constructs],
    [Direct Oblimin], [Oblique], [$\operatorname{Cov}(F_i, F_j) \neq 0$], [Tunable correlation ($\delta$)]
  )
]

// ============================================================================
// PART 5: COMPARISON & SUITABILITY
// ============================================================================

#slide[
  = Methodological Comparison: PCA vs. Factor Analysis

  #table(
    columns: (1.5fr, 2fr, 2fr),
    align: (left, left, left),
    table.header([*Dimension*], [*Principal Component Analysis (PCA)*], [*Factor Analysis (FA)*]),
    [Objective], [Maximize total variance explained], [Model latent causal constructs],
    [Variance Analyzed], [Total variance ($1.0$ on diagonal)], [Common variance ($h_j^2$ on diagonal)],
    [Error Term], [No explicit error modeling], [Explicit uniqueness $\boldsymbol{\varepsilon} \sim (0, \mathbf{\Psi})$],
    [Rotation], [Uncommon (alters variance maximization)], [Standard (Varimax/Promax)],
    [Assumptions], [Minimal distribution assumptions], [Multivariate normality for ML],
    [Best Used When], [Data compression, multicollinearity fix], [Construct validation, survey scales]
  )
]

#slide[
  = Pre-Analysis Suitability Checks

  Before extracting factors, evaluate correlation matrix factorability:

  #v(0.6em)

  *1. Kaiser-Meyer-Olkin (KMO) Measure of Sampling Adequacy:*
  - Quantifies proportion of variance among variables that might be common.
  - Scale: $> 0.9$ (Marvelous), $> 0.8$ (Meritorious), $> 0.7$ (Middling), $< 0.5$ (Unacceptable).

  #v(0.6em)

  *2. Bartlett's Test of Sphericity:*
  - $H_0: \mathbf{R} = \mathbf{I}_p$ (Variables are completely uncorrelated).
  - $H_1: \mathbf{R} \neq \mathbf{I}_p$.
  - Requires $p < 0.05$ to justify factor extraction.
]

// ============================================================================
// PART 6: PYTHON WORKFLOW & CASE STUDY
// ============================================================================

#slide[
  = Python Implementation: End-to-End Workflow

  ```python
  from factor_analyzer import FactorAnalyzer, calculate_kmo, calculate_bartlett_sphericity
  from sklearn.preprocessing import StandardScaler
  import pandas as pd

  # 1. Standardize indicators
  X_scaled = StandardScaler().fit_transform(df)

  # 2. Check suitability
  kmo_all, kmo_model = calculate_kmo(X_scaled)
  chi2_val, p_val = calculate_bartlett_sphericity(X_scaled)
  print(f"KMO: {kmo_model:.3f} | Bartlett p-value: {p_val:.4e}")

  # 3. Fit Factor Analysis with Varimax rotation
  fa = FactorAnalyzer(n_factors=3, rotation="varimax", method="principal")
  fa.fit(X_scaled)

  # 4. Inspect factor structure
  loadings = pd.DataFrame(fa.loadings_, index=df.columns, columns=["F1", "F2", "F3"])
  communalities = pd.Series(fa.get_communalities(), index=df.columns)
  ```
]

#slide[
  = Case Study: Educational Assessment (Chapter 4)

  *Context:* 200 high-school students evaluated across 9 cognitive and social performance measures:

  #grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 1.2em,
    [
      *Quantitative Ability*
      - MathScore
      - AlgebraScore
      - GeometryScore
    ],
    [
      *Verbal Ability*
      - ReadingComp
      - Vocabulary
      - Writing
    ],
    [
      *Interpersonal Skills*
      - Collaboration
      - Leadership
      - Communication
    ]
  )

  #v(0.8em)
  *Results:*
  - KMO = $0.84$ (Good) and Bartlett's test $p < 0.0001$.
  - Scree plot & Kaiser criterion confirm 3 distinct latent constructs.
  - Varimax rotation yields clean simple structure ($| \lambda | > 0.70$ on target factor, $< 0.20$ on others).
]

#slide[
  = Summary & Best Practices

  - *Use PCA* for data compression, image processing, and pre-processing for machine learning pipelines.
  - *Use Factor Analysis* when discovering or confirming latent psychological, educational, or financial traits.
  - Always report KMO ($> 0.60$) and Bartlett's test before interpreting factor models.
  - Choose *Varimax* for independent factor scores and *Promax* when latent traits are expected to interact.
  - Check communalities ($h^2 > 0.40$) to ensure observed variables are adequately represented.

  #v(1em)

  #align(center)[
    *Next Chapter: Chapter 5 — Discriminant Analysis (Supervised Classification)*
  ]
]
